export {default as Home} from "./Home/Home.jsx"
export {default as Challenges} from "./Challenges/Challenges.jsx"
export {default as MyRate} from "./MyRate/MyRate.jsx"
export {default as NewChallenge} from "./NewChallenge/NewChallenge.jsx"
export {default as Rating} from "./Rating/Rating.jsx"
export {SomeRating} from "./Rating/Rating.jsx"
export {default as RecentChallenges} from "./Home/RecentChallenges/RecentChallenges.jsx"
export {default as UpcomingChallenges} from "./Home/UpcomingChallenges/UpcomingChallenges.jsx"
export {default as SolveChallenge} from "./SolveChallenge/SolveChallenge.jsx"
